// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyD0QeWn4WTiOJVNegj-rkcKvSl7DLYNTik',
    appId: '1:455891680094:web:578ab09ab8362bda762dcf',
    messagingSenderId: '455891680094',
    projectId: 'shopping-list-app-840ca',
    authDomain: 'shopping-list-app-840ca.firebaseapp.com',
    databaseURL: 'https://shopping-list-app-840ca-default-rtdb.firebaseio.com',
    storageBucket: 'shopping-list-app-840ca.firebasestorage.app',
    measurementId: 'G-WR7J8NFT92',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyD0EDyGykOueASRA-bQr-oH1wOhOlbiyns',
    appId: '1:455891680094:android:262a3ea070c133c3762dcf',
    messagingSenderId: '455891680094',
    projectId: 'shopping-list-app-840ca',
    databaseURL: 'https://shopping-list-app-840ca-default-rtdb.firebaseio.com',
    storageBucket: 'shopping-list-app-840ca.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDnYWhOp-UWGFaTIOtiPT4lXihkpVFhsPE',
    appId: '1:455891680094:ios:1d6273d7f3494af1762dcf',
    messagingSenderId: '455891680094',
    projectId: 'shopping-list-app-840ca',
    databaseURL: 'https://shopping-list-app-840ca-default-rtdb.firebaseio.com',
    storageBucket: 'shopping-list-app-840ca.firebasestorage.app',
    iosBundleId: 'com.example.shoppingList',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyDnYWhOp-UWGFaTIOtiPT4lXihkpVFhsPE',
    appId: '1:455891680094:ios:1d6273d7f3494af1762dcf',
    messagingSenderId: '455891680094',
    projectId: 'shopping-list-app-840ca',
    databaseURL: 'https://shopping-list-app-840ca-default-rtdb.firebaseio.com',
    storageBucket: 'shopping-list-app-840ca.firebasestorage.app',
    iosBundleId: 'com.example.shoppingList',
  );

}